config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/projects'
  get 'pages/contact'
  root 'pages#home'
  get 'projects', to: 'pages#projects'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portafolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Portafolio</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Projects', projects_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contact', contact_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <img src="ruta_a_tu_imagen1.jpg" class="card-img-top" alt="Proyecto 1">
        <div class="card-body">
          <h5 class="card-title">Proyecto 1</h5>
          <p class="card-text">Descripción breve del proyecto.</p>
          <a href="#" class="btn btn-primary">Ver más</a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <img src="ruta_a_tu_imagen1.jpg" class="card-img-top" alt="Proyecto 1">
        <div class="card-body">
          <h5 class="card-title">Proyecto 1</h5>
          <p class="card-text">Descripción breve del proyecto.</p>
          <a href="#" class="btn btn-primary">Ver más</a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/projects.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <img src="ruta_a_tu_imagen1.jpg" class="card-img-top" alt="Proyecto 1">
        <div class="card-body">
          <h5 class="card-title">Proyecto 1</h5>
          <p class="card-text">Descripción breve del proyecto.</p>
          <a href="#" class="btn btn-primary">Ver más</a>
        </div>
      </div>
    </div>

  </div>
</div>